deployment:
  tasks:
    - echo "🚀 Desplegando Astro en modo estático..."

    - DEST_DIR="/home/apostill/public_html/v2"
    - echo "🧹 Limpiando destino: $DEST_DIR"
    - rm -rf "$DEST_DIR"
    - mkdir -p "$DEST_DIR"

    - echo "📂 Copiando archivos de dist/ a $DEST_DIR"
    - cp -r dist/* "$DEST_DIR/"

    - echo "✅ ¡Despliegue completado! Sitio activo en https://apostillacolombia.com/v2/"
